CREATE TABLE GENRE 
(
  GENRE_ID INTEGER NOT NULL 
, TITLE VARCHAR2(255) NOT NULL 
, DESCRIPTION VARCHAR2(512) 
, CONSTRAINT GENRE_PK PRIMARY KEY (GENRE_ID),
  CONSTRAINT GENRE_TITLE UNIQUE(TITLE)
  ENABLE 
);

CREATE SEQUENCE GENRE_ID_SEQ
	MINVALUE 1
	START WITH 1
	INCREMENT BY 1;

