CREATE TABLE USER_GENRE 
(
  APP_USER_FK INTEGER NOT NULL 
, GENRE_FK INTEGER NOT NULL
, CONSTRAINT USER_GENRE_COMB UNIQUE(APP_USER_FK, GENRE_FK)
, CONSTRAINT FK_APP_USER 
	FOREIGN KEY (APP_USER_FK)
	REFERENCES APP_USER (APP_USER_ID)
	ON DELETE CASCADE
, CONSTRAINT FK_GENRE 
	FOREIGN KEY (GENRE_FK)
	REFERENCES GENRE (GENRE_ID)
);

