CREATE TABLE APP_USER 
(
  APP_USER_ID INTEGER NOT NULL
, FIRST_NAME VARCHAR2(255) NOT NULL 
, LAST_NAME VARCHAR2(255) NOT NULL 
, EMAIL VARCHAR2(255) NOT NULL 
, SUBSCRIPTION_DATE TIMESTAMP NOT NULL 
, CONSTRAINT APP_USER_PK PRIMARY KEY (APP_USER_ID),
  CONSTRAINT APP_USER_EMAIL UNIQUE(EMAIL)
  ENABLE 
);

CREATE SEQUENCE APP_USER_ID_SEQ
	MINVALUE 1
	START WITH 1
	INCREMENT BY 1

CREATE TABLE APP_USER 
(
  USER_ID INTEGER NOT NULL PRIMARY KEY
, FIRST_NAME VARCHAR2(255) NOT NULL 
, LAST_NAME VARCHAR2(255) NOT NULL 
, EMAIL VARCHAR2(255) NOT NULL UNIQUE
, SUBSCRIPTION_DATE TIMESTAMP NOT NULL 
  ENABLE 
);
